# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform local_file resource.

    tf_gcp_project: "${var.gcp_project}"
    tf_region: "${var.region}"
    tf_zone: "${var.zone}"
    tf_cred_file: "${var.cred_file}"

    tf_control_instance_internal_ip: "${google_compute_instance.default.network_interface.0.network_ip}"
    tf_control_instance_external_ip: "${google_compute_address.static_external.address}"


    DOC
  filename = "../ansible/tf-ansible-vars-file.yaml"
}

resource "local_file" "tf_ansible_playbook_command" {
  content = <<-DOC
    # Generated by Terraform local_file resource.
    ANSIBLE_CONFIG='../${var.ansible_folder_name}/ansible.cfg' ansible-playbook -i ${google_compute_instance.default.network_interface.0.access_config.0.nat_ip}, --private-key ${local.private_ssh_key_path} ../${var.ansible_folder_name}/playbook-for-jenkins.yaml -v

    DOC
  filename = "../ansible/tf-ansible-playbook-command.yaml"
}
