- name: Create IP address
  hosts: localhost
  gather_facts: no

  vars:
    # project: my-project
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute
  vars_files:
    ./tf_ansible_vars_file.yaml

  tasks:

   - name: Allocate an IP Address
     gcp_compute_address:
         state: present
         name: 'test-address1'
         region: "{{ tf_region }}"
         project: "{{ tf_gcp_project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ tf_cred_file }}"
         scopes: "{{ scopes }}"

